### ISSUE TITLE
Support for data from the R10 flowcells

### ISSUE THREAD

**Issue by Y-Pei** [WGLab/NanoRepeat#12]
Hi, 

As the R9 flowcells are soon be discontinued by ONT, I was wondering would there be any support for the R10 flowcells in the future for NanoRepeat? 

Many thanks!

**Comment by kaichop** [comment]
it supports sequence data generated from R10 flowcell.

**Comment by Y-Pei** [comment]
The description of the -d doesn't seem to have an option for R10 though?

**Comment by fangli80** [comment]
Please use `-d ont_q20` if your read accuracy is Q20+ or above.
