### ISSUE TITLE
No expectation output

### ISSUE THREAD

**Issue by HLHsieh** [WGLab/NanoRepeat#15]
Hi Li,

I have used v1.4 for a long time, but some samples took a really long time to process. Therefore, I decided to try the new `--fast-mode` flag in the latest version. I tested it on a sample that was successfully analyzed in v1.4. However, I did not get the expected output as I did from the previous version.

The summary report from v1.4:
```
Summary_file=C9ORF72.chr9-27573528-27573546-GGCCCC.summary.txt	Repeat_Region=chr9-27573528-27573546-GGCCCC	Method=GMM	Num_Alleles=1	Num_Removed_Reads=0	Allele1_Num_Reads=4	Allele1_Repeat_Size=16
```
The output.tsv from v1.8:
```
chr9	27573528	27573546	GGCCCC	0	-1	-1	Allele_Repeat_Size;Allele_Num_Support_Reads	Read_Name;Read_Repeat_Size;Read_Allele_ID;PhasingConfidence
```
Additionally, the details folder only contained a `chr9` subfolder without any files inside it.

Any suggestions would be appreciated.

Best,
Hsin-Lun

**Comment by fangli80** [comment]
This is because your input is FASTA but not FASTQ. The v1.8 version has a bug that cannot process FASTA, which is fixed now. 
Please clone the latest version.

**Comment by HLHsieh** [comment]
Thank you. The issued was fixed.

**Comment by kaichop** [comment]
Thank you for letting us know. Close it now.
