### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by HLHsieh** [WGLab/NanoRepeat#16]
Hi Li,

I have some general questions about the usage and output. I would appreciate it if you could clarify them.

1) Difference between using FASTQ or BAM files: Are there any significant differences when using FASTQ or BAM files for quantification? I have a set of BAM files aligned by minimap2 with the -Y (soft clipping) option, but I noticed your script did not include this parameter for FASTQ input. Do you have any thoughts or suggestions on this matter?

2) About the output:
- Which output files (`repeat_size.txt`, `phased_reads.txt`, `summary.txt`, and `output.tsv`) should we consider first? I noticed the `summary.txt` and `output.tsv` are quite similar. I encountered a situation where only `repeat_size.txt` was generated, and I guess this might be due to an insufficient number of reads to support phasing.
- Are low phasing confidence reads removed when generating the summary report?

Thank you for your assistance.

Best regards,
Hsin

**Comment by fangli80** [comment]
Hello Hsin, 
There is no much difference between FASTQ and BAM input. NanoRepeat will realign the reads during analysis. 

The `output.tsv` include repeat quantification of multiple repeat regions. 
The `summary.txt` file for a specific repeat. If you have multiple repeat regions, there will be one `summary.txt` file for each repeat. 

The `repeat_size.txt` is the raw result for each read. 

Yes. When generating the summary report, some reads with low phasing confidence are removed.

**Comment by HLHsieh** [comment]
Hi Li,

Thank for your clear clarification!

Best,
Hsin
