### ISSUE TITLE
The regions that contain STR are unknown.

### ISSUE THREAD

**Issue by FAFUshiyan** [WGLab/NanoRepeat#2]
Hi Li,
This software must provide REPEAT_region.bed, I currently do not know those regions contain STR, is it not possible to use this software?

**Comment by fangli80** [comment]
Hello ShiYan,
Currently, NanoRepeat requires a reference sequence (consensus sequence) and the repeat location. (the repeat count in the reference sequence can be different from the sample)
If you have the reference sequence but don't know there the repeat is , you can use [Tandem Repeat Finder](https://tandem.bu.edu/trf/trf.html) to scan the reference sequence and get the repeat region. 

If you don't have the reference sequence (i.e., the consensus sequence is unknown), you can use a genome assembler (e.g., [wtdbg2](https://github.com/ruanjue/wtdbg2), [Flye](https://github.com/fenderglass/Flye), [metaFlye](https://doi.org/10.1038/s41592-020-00971-x) and [canu](https://github.com/marbl/canu)) to generate the consensus sequence and use `Tandem Repeat Finder` to scan the sequence to get the repeat region. 

In future versions, we will integrate these functions, but for now, please do these steps manually. 

Best, 
Li

**Comment by FAFUshiyan** [comment]
Thank you very much for your reply.
