### ISSUE TITLE
cite

### ISSUE THREAD

**Issue by windforclouds** [WGLab/NanoRepeat#3]
if we use it, how to cite?

**Comment by fangli80** [comment]
The manuscript is under revision and might be online in a few weeks. 

I uploaded the source code to zenodo. For now, it can be cited as: 

Fang, Li, & Wang, Kai. (2022). NanoRepeat: quantification of Short Tandem Repeats (STRs) from Oxford Nanopore sequencing data (v1.2). Zenodo. https://doi.org/10.5281/zenodo.7024485

**Comment by windforclouds** [comment]
thanks！

**Comment by fangli80** [comment]
Hello @windforclouds 
Our paper is online. If you use NanoRepeat, please cite: 

Li Fang, Alex Mas Monteys, Alexandra Dürr, Megan Keiser, Congsheng Cheng, Akhil Harapanahalli, Pedro Gonzalez-Alegre, Beverly L. Davidson, Kai Wang. Haplotyping SNPs for allele-specific gene editing of the expanded huntingtin allele using long-read sequencing. Human Genetics and Genomics Advances, 2022, DOI: https://doi.org/10.1016/j.xhgg.2022.100146.

Thanks, 
Li
