### ISSUE TITLE
Issue with repeat size

### ISSUE THREAD

**Issue by Cesco16** [WGLab/NanoRepeat#5]
Hi @fangli80 ,
thank you for this tool, i think it's great and very useful.
I used it for quantifying CAG repeats in a sample. It outputs 4 different alleles (basically 20,30,50 and 100 repeats) but, if I look at sequences present in the allele3.fastq file (50 repeats) it seems to over-estimate the number of repeats.
I show you one of the sequences of the allele3.fastq file and the corresponding repeat size estimate (from the repeat_size.txt file).

@7818cc7f-dc3d-476b-beeb-38d6d52a40e0
CTTCAATTTCCCGAGTAAG**CAG**G**CAG**AGATCGCGGACGCTACCC**CAG**AG**CAG**GGCGTCATGCGCGAGAGAAAGCTTTGCACTTTGCGAACCAACGATAGGTGGGGGTGCGTGGAGGATGGAACACGGACGGCCCGGCTTGCTGCCTTTCC**CAG**GCCTG**CAG**GTTTGCCCATCCACGT**CAG**GGCCT**CAG**CCTGGCCGAAAAGAAATGGTCTGTGATCCCC**CAGCAGCAGCAGCAGCAGCAG**CGGCGGCGGCGGCGTTTCCCCGGCTACAAGGACCCTTCGAGCCCGTTCGCCGGCCGCGGACCCGGCCCCTCCCTCCCCCGGCCGCTGGGGGCGGGCCCGGATCA**CAG**GACTGGAGCTGGGCGGAGACCCACGCTCGGAGCGGTTGTGAACTGG**CAG**GCGGTGGGCGCGGCTTCTGTGCCGTGCCCGGGCACT**CAG**TCTTCCAACGGGGCCCCGGAGTCGAAGA**CAG**TTCTAGGGTT**CAG**GGAGCGCGGGCGGCTGCCTGGGCGGCGC**CAG**ACTGCGGTGAGTTGGCCGGCGTGGGCCACCAACCCAATG**CAG**CC**CAG**GGCGGCGG

7818cc7f-dc3d-476b-beeb-38d6d52a40e0	**50.5**

As you can see, in the sequence there are about 20 repeats, while the number of estimated repeats is above 50.
Any ideas of why such a behaviour? Is there any sort of error rate parameter which count also motifs similar to CAG?
Thank you very much in advance!

**Comment by fangli80** [comment]
NanoRepeat assumes that all bases in the specified region are the same motif and cannot handle repeats of mixed motifs. This is the current limitation of NanoRepeat. 

For example, if the bed file include the following, 
`chr4	3074876	3074939	CAG`
NanoRepeat will assume that all bases mapped to `chr4:3074876-3074939` are CAG repeats. 

We may fix this in a later version. For now, if you want to quantify CAG repeats in the fastq, please set start and end position according to the following figure. (assuming that the region flanking CAG repeats exits in the reference genome )
![image](https://user-images.githubusercontent.com/9782948/227254710-fa17627f-3fb4-45c5-a922-dfff99fc55e4.png)

Best, 
Li

**Comment by fangli80** [comment]
By the way, I'm curious if your sample does contain multiple alleles?
